sudo: false
language: cpp
compiler: clang
env:
  - MO_WITH_ADDRESS_SANITIZER=OFF
  - MO_WITH_ADDRESS_SANITIZER=ON
cache:
  apt: true
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - lcov
      - libjpeg-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglu1-mesa-dev
before_install:
  - gem install coveralls-lcov
  - sh ./utilities/download_gtest.sh
  - sh ./utilities/download_glfw.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DMO_ENABLE_COVERAGE=ON -DMO_BUILD_TESTS=ON -DBUILD_GTEST=ON -DBUILD_GMOCK=OFF -Dgtest_disable_pthreads=ON -Dgtest_hide_internal_symbols=ON -DCMAKE_CXX_COMPILER=${COMPILER} -DBUILD_SHARED_LIBS=ON -DMO_WITH_ADDRESS_SANITIZER=${MO_WITH_ADDRESS_SANITIZER} -DMO_WITH_WALL_FLAGS=ON -DMO_WITH_PEDANTIC_FLAGS=ON -DMO_WITH_WARNING_AS_ERRORS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_INSTALL=OFF ..
  - make -j2 VERBOSE=1
  - ctest -j2 --output-on-failure
after_success:
  - lcov -d tests -d src -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'gtest*' -o coverage.info
  - lcov --remove coverage.info 'glfw*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
